### ISSUE TITLE
contextHandle per block setting not working

### ISSUE THREAD

**Issue by daltonrooney** [madebyraygun/craft-block-loader#6]
Given a block with the following settings definition:

```php
    protected function onInit(ContextBlockSettings $settings): void
    {
        $settings
            ->contextHandle('banner')
            ->matrixHandle('banner');
    }
```

The context for this block should be added to the `banner` object, but it's still being added to the `blocks` object.

**Comment by daltonrooney** [comment]
@vanrez-nez I'm going to take a look into this but I may need your help! 😀

Edit: my mistake, I misunderstood what `contextHandle` is. I'm actually looking for a block setting that can override the `globalContextHandle` and create multiple top-level context objects.

If I'm understanding correctly, I think we may want to rename `contextHandle` to `templateHandle`. Let me submit a PR and you can take a look?

**Comment by vanrez-nez** [comment]
@daltonrooney I'm working on a different aproach in https://github.com/madebyraygun/craft-block-loader/tree/feature/4-ckeditor-support where I'm deprecating hooks in favor of behaviors. This will provide the flex we need for cases like this since the plugin is not in charge of "injecting" anything anymore:

So for any Matrix Field or CKEditor fields our blocks loop will look like this:
```twig
{% set blocks = entry.blocksFromField('contentBlocks') %}
{% for item in blocks %}
  {% include '@cb-' ~ item.handle with item.context %}
{% endfor %}
```

in the same way if banners is just a matrix field we would just need to change the field name:
```twig
{% set banners = entry.blocksFromField('banners') %}
{% for banner in banners %}
  {% include '@' ~ item.handle with banner.context %}
{% endfor %}
```

I'm about to finish this branch and make a PR in a few hours so we can discuss it and see if we still need to support the old implementation for hooks?

**Comment by daltonrooney** [comment]
@vanrez-nez That's amazing! I'll hold off on any changes until we have an opportunity to review your PR. Sounds like a very sensible approach 👍🏻
